### ISSUE TITLE
Install dependency gems always fails

### ISSUE THREAD

**Issue by blacklevel7** [algobasket/PeatioCryptoExchange#57]
Hi, @algobasket 
Step #Install dependency gems always fails... :(

**Installing on ubuntu 16 with ruby  -v 2.2.2:**
```
Gem::InstallError: active_hash requires Ruby version >= 2.4.0.
An error occurred while installing active_hash (2.1.0), and Bundler cannot continue.
Make sure that gem install active_hash -v '2.1.0' succeeds before bundling.

gem install active_hash -v '2.1.0'
ERROR:  Error installing active_hash:
        i18n requires Ruby version >= 2.3.0.
```
---------
**Installing on ubuntu 16 with ruby  -v 2.3.0:**
```
Gem::InstallError: active_hash requires Ruby version >= 2.4.0.
An error occurred while installing active_hash (2.1.0), and Bundler cannot continue.
Make sure that `gem install active_hash -v '2.1.0'` succeeds before bundling.
```

------
**Installing on ubuntu 16 with ruby  -v 2.4.0:**
```
NoMethodError: undefined method `spec' for nil:NilClass
An error occurred while installing unread (0.4.0), and Bundler cannot continue.
Make sure that `gem install unread -v '0.4.0'` succeeds before bundling.
```
-------
**Installing on ubuntu 16 with ruby  -v 2.5.3:**
```
NoMethodError: undefined method `spec' for nil:NilClass
An error occurred while installing unread (0.4.0), and Bundler cannot continue.
Make sure that `gem install unread -v '0.4.0'` succeeds before bundling.
```

**gem install unread -v '0.4.0' nothing changes**

**installing with installer also fails on ./PEATIO-INSTALLER-THREE.sh**

_My VM has 2 cores, 2 GB RAM and 50 GB SSD disk._

**_Please help! :)_**

**Comment by dagnyc** [comment]
@blacklevel7 Welcome to Algobasket. This used to work with ruby 2.2.2 and bundler 1.9.2 BUT now it won't work at all with any version of anything. Forget it. The gem bootstrap-sass-3.2.0.2 is needed but no longer available. Until @algobasket fixes this to work with a newer version like bootstrap-sass-3.2.0.4 or newer it's totally dead in the water.

**Comment by blacklevel7** [comment]
... :)

**Comment by algobasket** [comment]
rbenv install -v 2.2.1 | rbenv install -v 2.2.2 | rbenv install -v 2.2.7
gem install bundler -v 1.9.2
and bootstrap-sass 3.2.0.4
Enjoy !

**Comment by blacklevel7** [comment]
`deploy@peatio-algobasket:~$ gem install bootstrap-sass 3.2.0.4
Fetching: ffi-1.10.0.gem (100%)
Building native extensions.  This could take a while...
Successfully installed ffi-1.10.0
Fetching: sassc-2.0.1.gem (100%)
ERROR:  Error installing bootstrap-sass:
        sassc requires Ruby version >= 2.3.3.
ERROR:  Could not find a valid gem '3.2.0.4' (>= 0) in any repository
`
:(

**Comment by blacklevel7** [comment]
`NoMethodError:` undefined method `spec' for nil:NilClass
An error occurred while installing unread (0.4.0), and Bundler cannot `continue.`

**Comment by blacklevel7** [comment]
https://github.com/ledermann/unread/blob/master/lib/unread/version.rb

**Comment by blacklevel7** [comment]
Hi @algobasket
I still have the same error with 
 gem 'unread', github: 'InfraexDev/unread'

If I comment out this gem, bundler was finished, but application wont start.. "Web application could not be started by the Phusion Passenger application server."

**Comment by pankaj9310** [comment]
@blacklevel7 
```
Use this gem gem 'unread', github: 'ledermann/unread' in place of
gem 'unread', github: 'InfraexDev/unread'
```
